### PR TITLE
modify All onClick and revert jsonrcp settings to previous one

### PR DESCRIPTION
**Pull request by joyfun**
have remove all onclick and submit action 
and revert the the jsonrcp setting

### CODE REVIEW

**Comment by binux** [comment]
You didn't bind onsubmit events...

**Comment by joyfun** [comment]
there are 2 onsubmit event 
i use click event to replace it
      $("#add-task-submit").live("click", function() {
   		YAAW.add_task.submit();return false;
      });

      $("#saveSettings").live("click", function() {
   		YAAW.setting.submit();return false;
      });

**Comment by joyfun** [comment]
in  event_init  i use click to replace it 
       $("#add-task-submit").live("click", function() {
    		YAAW.add_task.submit();return false;
       });

      $("#saveSettings").live("click", function() {
   		YAAW.setting.submit();return false;
      });

**Comment by binux** [comment]
click to save button make it can't submit in url input via enter button.

**Comment by joyfun** [comment]
i add a submit bind in lastest commit
https://github.com/joyfun/yaaw/commit/a83fdba2c8b776364b51c81d27944518781801bd

**Pull request merged**
